CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(255),
    due_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'TODO',
    title VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_task_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE'))
);

INSERT INTO projects (name, description)
VALUES ('Inbox', 'Default project for uncategorized tasks');
